### ISSUE TITLE
Can this run on the PS2 itself?

### ISSUE THREAD

**Issue by faissaloo** [ZirconiumX/ps2-clang-patches#7]
Hello! I'm exploring creating a bare bones PS2 Linux distro that can run off a disc without requiring FMCB or a modchip. The main thing I'm looking for is a compiler that will actually run on the PS2 so it can actually be used for writing new software without depending on cross-compilation, could this project do that?
I'm planning to base it on Maximus32's 3.8 kernel since it's the newest I've found.

**Comment by rickgaiser** [comment]
Latest linux development is by frno7, here: https://github.com/frno7/linux

New compilers require too much RAM to be used on a ps2 natively.

**Comment by faissaloo** [comment]
Awesome, thanks for pointing me in the right direction.
As for compilers I guess I'll just stick to an old version of GCC then, it's better than nothing
